# Generated by Django 5.2.8 on 2025-12-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='search_title',
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
    ]
