# Generated by Django 5.2.8 on 2025-12-15 18:54

from django.db import migrations
from unidecode import unidecode

## caso o campo search_title já exista, mas precise popular os dados:

def normalize_existing_titles(apps, schema_editor):
    """
    Normaliza o campo search_title para todos os produtos existentes.
    """
    Product = apps.get_model('products', 'Product') # Obter o modelo da app 'products'
    
    # Percorre todos os produtos no banco
    for product in Product.objects.all():
        # Aplica a lógica de normalização que está no seu método save()
        if product.title:
            product.search_title = unidecode(product.title).lower()
            # Salva *apenas* o campo search_title, sem rodar o método save()
            # do modelo, para evitar loops ou efeitos colaterais.
            product.save(update_fields=['search_title'])

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_search_title'),
    ]

    operations = [
        # execução da função de normalização .noop é para o caso de precisar de um reverso vazio
        migrations.RunPython(normalize_existing_titles, migrations.RunPython.noop),
    ]
